name = "LamTaczServer"
author = "LamPT"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6deff8bf4e4a711d9ca2f0462255b198af203289dee3e61fce19061284e2fa96"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
