name = "LamTaczServer"
author = "LamPT"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce59cb0339d976683bf648cb6c56e4e777e4778288dd6f22bacf099fad04acf"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
